require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0
  Include:
    - "**/*.rake"
    - "**/*.rb"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - bin/**/*
    - tmp/**/*
    - config/**/*
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
RSpec/ExampleLength:
  Max: 20
RSpec/DescribeClass:
  Enabled: false
