require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0
  Include:
    - "**/*.rake"
    - "**/*.rb"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - tmp/**/*
    - config/**/*
    - spec/**/*
  NewCops: enable

Style/Documentation:
  Enabled: false
